# Generated by Django 3.1.2 on 2020-10-18 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team_code', models.CharField(max_length=50)),
                ('managed_by', models.ManyToManyField(related_name='managed', to=settings.AUTH_USER_MODEL)),
                ('parent_team_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parentcode', to='blog.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membercode', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('member_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='membername', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team', to='blog.team')),
            ],
        ),
    ]
