# Generated by Django 3.1.2 on 2020-10-18 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_team_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='managed_by',
        ),
        migrations.AddField(
            model_name='team',
            name='managed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed', to='auth.user'),
            preserve_default=False,
        ),
    ]
