# Generated by Django 3.1.2 on 2020-10-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201018_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='parent_team_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parentcode', to='blog.team'),
        ),
    ]
